Document: editeur-universel
Title: Debian editeur-universel Manual
Author: <insert document author here>
Abstract: This manual describes what editeur-universel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/editeur-universel/editeur-universel.sgml.gz

Format: postscript
Files: /usr/share/doc/editeur-universel/editeur-universel.ps.gz

Format: text
Files: /usr/share/doc/editeur-universel/editeur-universel.text.gz

Format: HTML
Index: /usr/share/doc/editeur-universel/html/index.html
Files: /usr/share/doc/editeur-universel/html/*.html
